[package]
name = "graphics"
authors.workspace = true
edition.workspace = true
version.workspace = true
description.workspace = true

[dependencies]
toyengine_core = { package = "core", path = "../core" }
