[workspace]
resolver = "3"
members = ["core", "graphics"]
[workspace.package]
authors = ["Werberth Lins <halkliff@pm.me>"]
edition = "2024"
version = "0.1.0"
description = "A toy Graphics and Game Engine"
